language: java

services:
  - docker

dist: trusty
sudo: false

# Get latest install-jdk.sh script
before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

matrix:
  include:
# Java 11 "OpenJDK"
    - env: JDK='OpenJDK 11'
      install: . ./install-jdk.sh -F 11 -L GPL

script:
  - ./gradlew build
